/**
 * Export Utilities
 *
 * Export expenses and balances as CSV for sharing
 */

import { Share, Platform } from 'react-native';
import { Split4UsExpense } from './api';

// expo-file-system is optional — only needed for mobile file-based sharing
let FileSystem: any = null;
try {
  FileSystem = require('expo-file-system');
} catch {
  // Not installed — fallback to text sharing on mobile
}
import { formatAmount, formatDate, getCategoryById } from './utils';

/**
 * Generate CSV string from expenses
 */
export function expensesToCSV(
  expenses: Split4UsExpense[],
  groupName?: string
): string {
  const header = 'Date,Description,Category,Amount,Currency,Paid By,Notes';
  const rows = expenses.map((exp) => {
    const cat = getCategoryById(exp.category);
    const paidBy = exp.paid_by_user?.full_name || exp.paid_by_user?.email || exp.paid_by;
    const notes = (exp.notes || '').replace(/"/g, '""');
    return `${formatDate(exp.date)},"${exp.description}","${cat.name}",${exp.amount},${exp.currency},"${paidBy}","${notes}"`;
  });

  const title = groupName ? `# ${groupName} - Expenses Export\n` : '';
  return `${title}${header}\n${rows.join('\n')}`;
}

/**
 * Share expenses as CSV via system share sheet
 */
export async function shareExpensesCSV(
  expenses: Split4UsExpense[],
  groupName?: string
): Promise<void> {
  const csv = expensesToCSV(expenses, groupName);
  const filename = `split4us_expenses_${new Date().toISOString().split('T')[0]}.csv`;

  if (Platform.OS === 'web') {
    // Web: download directly
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
    return;
  }

  // Mobile: write temp file and share
  const filePath = `${FileSystem?.documentDirectory || ''}${filename}`;

  if (FileSystem?.writeAsStringAsync) {
    await FileSystem.writeAsStringAsync(filePath, csv);
    await Share.share({
      url: filePath,
      title: `Split4Us Export - ${groupName || 'All Expenses'}`,
    });
  } else {
    // Fallback: share as text
    await Share.share({
      message: csv,
      title: `Split4Us Export - ${groupName || 'All Expenses'}`,
    });
  }
}

/**
 * Generate a summary text for sharing
 */
export function generateBalanceSummary(
  balances: { name: string; amount: number; currency: string }[],
  groupName: string
): string {
  const lines = [
    `💰 ${groupName} - Balance Summary`,
    `📅 ${formatDate(new Date())}`,
    '',
    ...balances.map((b) => {
      const sign = b.amount >= 0 ? '+' : '';
      return `${b.name}: ${sign}${formatAmount(b.amount, b.currency)}`;
    }),
    '',
    'Generated by Split4Us',
  ];
  return lines.join('\n');
}

/**
 * Share balance summary via system share sheet
 */
export async function shareBalanceSummary(
  balances: { name: string; amount: number; currency: string }[],
  groupName: string
): Promise<void> {
  const summary = generateBalanceSummary(balances, groupName);
  await Share.share({
    message: summary,
    title: `${groupName} - Balances`,
  });
}
