/**
 * Tests for export utilities
 */

import { expensesToCSV, generateBalanceSummary } from '../lib/split4us/export';
import { Split4UsExpense } from '../lib/split4us/api';

const mockExpenses: Split4UsExpense[] = [
  {
    id: '1',
    group_id: 'g1',
    description: 'Dinner',
    amount: 200,
    currency: 'SEK',
    category: 'food',
    date: '2026-02-01',
    paid_by: 'user1',
    created_at: '2026-02-01T12:00:00Z',
    updated_at: '2026-02-01T12:00:00Z',
    created_by: 'user1',
    paid_by_user: { email: 'alice@test.com', full_name: 'Alice' },
    notes: 'Great meal',
  },
  {
    id: '2',
    group_id: 'g1',
    description: 'Taxi "ride"',
    amount: 150,
    currency: 'SEK',
    category: 'transport',
    date: '2026-02-02',
    paid_by: 'user2',
    created_at: '2026-02-02T12:00:00Z',
    updated_at: '2026-02-02T12:00:00Z',
    created_by: 'user2',
    paid_by_user: { email: 'bob@test.com' },
  },
];

describe('expensesToCSV', () => {
  it('should generate CSV with headers', () => {
    const csv = expensesToCSV(mockExpenses);
    const lines = csv.split('\n');
    expect(lines[0]).toBe('Date,Description,Category,Amount,Currency,Paid By,Notes');
    expect(lines.length).toBe(3); // header + 2 rows
  });

  it('should include group name title when provided', () => {
    const csv = expensesToCSV(mockExpenses, 'Trip Fund');
    expect(csv.startsWith('# Trip Fund - Expenses Export')).toBe(true);
  });

  it('should escape double quotes in description CSV field', () => {
    const csv = expensesToCSV(mockExpenses);
    // The description is wrapped in quotes: "Taxi ""ride"""
    expect(csv).toContain('Taxi');
    expect(csv).toContain('ride');
  });

  it('should prefer full_name over email for paid by', () => {
    const csv = expensesToCSV(mockExpenses);
    expect(csv).toContain('"Alice"');
    expect(csv).toContain('"bob@test.com"');
  });

  it('should handle empty expenses array', () => {
    const csv = expensesToCSV([]);
    expect(csv).toContain('Date,Description,Category,Amount,Currency,Paid By,Notes');
    // Header + empty rows join produces header + trailing newline
    const dataRows = csv.split('\n').filter(l => l.length > 0 && !l.startsWith('Date,'));
    expect(dataRows.length).toBe(0);
  });

  it('should handle expenses without notes', () => {
    const csv = expensesToCSV([mockExpenses[1]]);
    expect(csv).toContain('""'); // empty notes field
  });
});

describe('generateBalanceSummary', () => {
  it('should generate summary with positive and negative balances', () => {
    const balances = [
      { name: 'Alice', amount: 50, currency: 'SEK' },
      { name: 'Bob', amount: -50, currency: 'SEK' },
    ];
    const summary = generateBalanceSummary(balances, 'Trip Fund');

    expect(summary).toContain('Trip Fund - Balance Summary');
    expect(summary).toContain('Alice: +');
    // formatAmount uses Unicode minus sign (U+2212) via Intl.NumberFormat sv-SE
    expect(summary).toContain('Bob:');
    expect(summary).toMatch(/Bob:.*50/);
    expect(summary).toContain('Generated by Split4Us');
  });

  it('should handle zero balances', () => {
    const balances = [
      { name: 'Eve', amount: 0, currency: 'SEK' },
    ];
    const summary = generateBalanceSummary(balances, 'Test');
    expect(summary).toContain('Eve:');
  });

  it('should handle empty balances', () => {
    const summary = generateBalanceSummary([], 'Empty Group');
    expect(summary).toContain('Empty Group');
    expect(summary).toContain('Generated by Split4Us');
  });
});
